// flow-typed signature: 29c1d3c6576044fc15433e4a5c38df7e
// flow-typed version: <<STUB>>/git-validate_v^2.2.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-validate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-validate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-validate/bin/install' {
  declare module.exports: any;
}

declare module 'git-validate/lib/utils' {
  declare module.exports: any;
}

declare module 'git-validate/test/utils' {
  declare module.exports: any;
}

declare module 'git-validate/test/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-validate/bin/install.js' {
  declare module.exports: $Exports<'git-validate/bin/install'>;
}
declare module 'git-validate/index' {
  declare module.exports: $Exports<'git-validate'>;
}
declare module 'git-validate/index.js' {
  declare module.exports: $Exports<'git-validate'>;
}
declare module 'git-validate/lib/utils.js' {
  declare module.exports: $Exports<'git-validate/lib/utils'>;
}
declare module 'git-validate/test/utils.js' {
  declare module.exports: $Exports<'git-validate/test/utils'>;
}
declare module 'git-validate/test/validate.js' {
  declare module.exports: $Exports<'git-validate/test/validate'>;
}
