// flow-typed signature: 0a22cfdfbb4e7812aa23ddb98433c741
// flow-typed version: <<STUB>>/gulp-rename_v^1.4.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-rename'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-rename' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-rename/index' {
  declare module.exports: $Exports<'gulp-rename'>;
}
declare module 'gulp-rename/index.js' {
  declare module.exports: $Exports<'gulp-rename'>;
}
