// flow-typed signature: a38b27716f7257998c0c1a3aa0af0cf3
// flow-typed version: <<STUB>>/gulp-task-doc_v^1.0.11/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-task-doc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-task-doc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-task-doc/lib/models' {
  declare module.exports: any;
}

declare module 'gulp-task-doc/lib/parser' {
  declare module.exports: any;
}

declare module 'gulp-task-doc/lib/printer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-task-doc/index' {
  declare module.exports: $Exports<'gulp-task-doc'>;
}
declare module 'gulp-task-doc/index.js' {
  declare module.exports: $Exports<'gulp-task-doc'>;
}
declare module 'gulp-task-doc/lib/models.js' {
  declare module.exports: $Exports<'gulp-task-doc/lib/models'>;
}
declare module 'gulp-task-doc/lib/parser.js' {
  declare module.exports: $Exports<'gulp-task-doc/lib/parser'>;
}
declare module 'gulp-task-doc/lib/printer.js' {
  declare module.exports: $Exports<'gulp-task-doc/lib/printer'>;
}
