// flow-typed signature: a59ed000ca602d5dccd3ba75f10014db
// flow-typed version: <<STUB>>/react-native-image-processor_vhttps://github.com/Elf2707/react-native-image-processor.git/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-processor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-processor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-image-processor/index' {
  declare module.exports: $Exports<'react-native-image-processor'>;
}
declare module 'react-native-image-processor/index.js' {
  declare module.exports: $Exports<'react-native-image-processor'>;
}
