// flow-typed signature: 1d7ff3fe32ce509a891ac1d5a16ac8cb
// flow-typed version: <<STUB>>/react-native-logger_v^1.0.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-logger/index' {
  declare module.exports: $Exports<'react-native-logger'>;
}
declare module 'react-native-logger/index.js' {
  declare module.exports: $Exports<'react-native-logger'>;
}
